server:
  port: 7833

logging:
  level:
    soya.framework: DEBUG

camel:
  springboot:
    name: ServicesRest

management:
  port: 8081

endpoints:
  enabled: false
  health:
    enabled: true

quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s

soya:
  framework:
    api:
      path: '/camel'