server:
  port: 8080

spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: absitdsdevwusseddw001
          account-key: yYF0293O1dHvHwfwKektJa3ptAMgH219Pp7886kyqQ/1EHivjCL4L9Dy+W/mx1JyjM+BEVqHC3xvSKkzKrbz7g==
          endpoint: https://absitdsdevwusseddw001.blob.core.windows.net

soya:
  framework:
    action:
      scanPackages: soya.framework

      kafka:
        factory: kafka-core-qa.properties, kafka-core-dev.properties, kafka-platform-qa.properties, kafka-platform-dev.properties

albertsons:
  workspace:
    home: C:/albertsons/workspace