server:
  port: 8080

soya:
  framework:
    property: www
    name: Wen Qun
    restruts:
      scanPackages: soya.framework.restruts.reflect,soya.framework.restruts.tool,soya.framework.spring.actions